# Session(04-06-20)

## NUMPY Package
1. Numerical data
2. Computations on numerics


In [3]:
import numpy as np

### DIFFEREMCES BETWEEN NUMPY ARRAY AND LISTS
1. Convinient
2. Faster
3. Less memory

In [4]:
# 1d array
a = np.array([1,2,3,4,5])
print(a)

array([1, 2, 3, 4, 5])

In [9]:
a1 = np.array([[1,2,3],[1,3,4],[2,4,6]])
print(a1)
print(a1.ndim) # dimension
print(a1.shape)   # rows,columns--->gives a tuple(r,c)
print(a1.shape[0],a1.shape[1])

[[1 2 3]
 [1 3 4]
 [2 4 6]]
2
(3, 3)
3 3


In [14]:
# 1.using user input for array
a = np.array([],dtype="int32")
a = np.append(a,int(input()))
print(a.dtype)  #gives datatype
print(a)

15
int32
[15]


In [19]:
# 2.Appending a list to array
a = np.append(a,[1,2,3,4,5,6,7])
print(a.dtype,a) ## default type is float64

int32 [15  1  2  3  4  5  6  7  1  2  3  4  5  6  7  1  2  3  4  5  6  7  1  2
  3  4  5  6  7  1  2  3  4  5  6  7]


### Slicing

In [22]:
a1 = np.array([12,223,34,45,56,67])
a1

array([ 12, 223,  34,  45,  56,  67])

In [23]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
print(a1[1])
print(a2[1,1]) #row, col indices  [r,c]
print(a2[1:,:3])# ranges->[r1:r2,c1:c2] r1<r2,c1<c2
print(a2[1,0:-1])

223
5
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[4 5]


In [35]:
print(a2[0::2,:])  ## for setting step value
# it gives alternate rows

[[1 2 3]
 [7 8 9]]


## Iterate through array:

In [36]:
for row in a2:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [39]:
list1 = [[1,2],[3,4]]
for i in list1:
    print(i)

[1, 2]
[3, 4]


In [42]:
# for iterating all elemnets in order
for ele in a2.flat:
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [47]:
np.array(a2.flat)  # it flatens in one d array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [49]:
np.array(a2).ravel() # also used for converting into 1d array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### INDEXING WITH BOOLEAN ARRAY

In [52]:
a = np.arange(1,21).reshape(5,4) #reshape for giving r,c
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [60]:
r = a%5==0
r

array([[False, False, False, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [61]:
a[r] ## returning only true values

array([ 5, 10, 15, 20])

In [67]:
# vertical stacking for vstack,hstack sizes of 2 arrays are same
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(11,20).reshape(3,3)
print(np.vstack((a1,a2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [68]:
# horizontal stacking
print(np.hstack((a1,a2)))

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


### Attribute:
1. size
2. ndim
3. shape
4. itemsize
5. dtype

In [69]:
a = np.arange(1,11).reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [72]:
print(a.size)     #total elements
print(a.itemsize) #size of each
print(a.ndim)     #1d,2d,3d,.....
print(a.shape)    #tuple(r,c)
print(a.dtype)    #datatype

10
4
2
(2, 5)
int32


### Functions
1. zeros()
2. ones()
3. full()
4. eye()
5. linspace()
6. reshape()
7. arange()
8. ravel()

In [75]:
np.zeros((2,3),dtype="int32")

array([[0, 0, 0],
       [0, 0, 0]])

In [77]:
np.zeros((2,3),)   #default type is float64

array([[0., 0., 0.],
       [0., 0., 0.]])

In [78]:
np.full((4,4),"s")

array([['s', 's', 's', 's'],
       ['s', 's', 's', 's'],
       ['s', 's', 's', 's'],
       ['s', 's', 's', 's']], dtype='<U1')

In [81]:
e = np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [84]:
# linspace()   ->lineaer space array
# divides into k equal parts linspace(range1,r2,k)
np.linspace(1,10,5) 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [88]:
np.arange(1,12,2)  #(start,stop,range)

array([ 1,  3,  5,  7,  9, 11])

In [89]:
np.array(e.flat)

array([1, 0, 0, 0, 1, 0, 0, 0, 1])

In [90]:
np.array(a.ravel())

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Functions:
1. min()
2. max()
3. sum()
4. sqrt()
5. mean()
6. median()

In [97]:
print(a)
print(a.min())
print(a.max())
print(a.sum())
print(a.sum(axis=1)) #row sum if axis=1
print(a.sum(axis=0)) # col sum axis=0

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1
10
55
[15 40]
[ 7  9 11 13 15]


In [98]:
print(np.sqrt(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))

[[1.         1.41421356 1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712 3.         3.16227766]]
5.5
5.5
2.8722813232690143


## Mathematical operations :+-*/%

In [106]:
a = np.arange(1,10)
b = np.arange(10,19)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

[1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18]
[11 13 15 17 19 21 23 25 27]
[-9 -9 -9 -9 -9 -9 -9 -9 -9]
[ 10  22  36  52  70  90 112 136 162]
[0.1        0.18181818 0.25       0.30769231 0.35714286 0.4
 0.4375     0.47058824 0.5       ]
[1 2 3 4 5 6 7 8 9]


### dot()--> matrix multiplication
#### a= mxn ;b= nxl

In [108]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
a.dot(b)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

# T attribute for transpose

In [109]:
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Applying userdefined function:

In [113]:
list1 = list(range(1,20))
r = [c/(c+1) for c in list1]
print(r)
a = np.array(list1)
a

[0.5, 0.6666666666666666, 0.75, 0.8, 0.8333333333333334, 0.8571428571428571, 0.875, 0.8888888888888888, 0.9, 0.9090909090909091, 0.9166666666666666, 0.9230769230769231, 0.9285714285714286, 0.9333333333333333, 0.9375, 0.9411764705882353, 0.9444444444444444, 0.9473684210526315, 0.95]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [114]:
f = np.vectorize(lambda x:x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])