<a href="https://colab.research.google.com/github/PrasadReddyGaddam/PYTHON/blob/master/05_06_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Session(05-06-20)

In [7]:
from numpy import random
print(random.randint(1,100)) #random int in range
print(random.rand())   #float(0,1) 

97
0.2943142844656679


In [10]:
# createing n dim array with int values
print(random.randint(100,size=(3,)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[76 21 34]
[[ 2 30 76 43]
 [24 88 72 80]
 [ 8 14 14 97]]
[[[ 4 42]
  [70  0]
  [15 31]
  [38  4]]

 [[69 52]
  [17 77]
  [78 50]
  [37 37]]

 [[55 78]
  [73 44]
  [57 22]
  [28 39]]]


In [20]:
# createing n dim array with float values
print(random.rand(3 ))  #1d
print(random.rand(3,2))  #2d
print(random.rand(3,4,2)) #3d

[0.34252125 0.2391143  0.19117298]
[[0.79182024 0.36200479]
 [0.87861838 0.55446502]
 [0.79474951 0.75304518]]
[[[0.26689156 0.12602911]
  [0.66044656 0.30814556]
  [0.90315463 0.45169628]
  [0.92237416 0.08079948]]

 [[0.36335117 0.63608312]
  [0.92490024 0.77855711]
  [0.29481974 0.91189728]
  [0.23209367 0.1953617 ]]

 [[0.4367922  0.99532748]
  [0.29462558 0.86913384]
  [0.81489191 0.62093839]
  [0.00754367 0.9058175 ]]]


In [33]:
a = random.randint(100 ,size=(3,2)).ravel()
random.choice(a)    # choice function only for 1d


44

In [34]:
# for generating an array with given elements only and sizes
a = random.choice([1,2,3,4,5],size=(3,3))
a

array([[2, 2, 5],
       [3, 5, 2],
       [2, 4, 3]])

Pandas
1. Data manipulation,analysis and data cleaning
2. Tabular data,unlabelled data

In [40]:
#1. creating a data frames using 2 dictionaries
import pandas as pd
import numpy as np
dict1 = {"a":1,"b":2,"c":3,"d":4,"e":5}
dict2 = {"a":6,"b":7,"c":8,"d":9,"e":5}
data ={"first":dict1,"second":dict2}
df = pd.DataFrame(data,dtype="int32")
df

first  second
a      1       6
b      2       7
c      3       8
d      4       9
e      5       5

In [43]:
#2. coverting a simple dictionary to dataframe
d1 = {"name":["a","d","r","t"],"address":["1","2","3","4"]}
df1 = pd.DataFrame(d1)
df1

name address
0    a       1
1    d       2
2    r       3
3    t       4

In [46]:
#3. Using series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.1,23.4,34.4,54.4,65.4,67.9,78.8,98.6,11.4,45.47])
s3 = pd.Series(["a","b","c","d","e","f","g","h","i","j"])
data = {"c1":s1,"c2":s2,"c3":s3}
dd = pd.DataFrame(data)
dd

c1     c2 c3
0   1  12.10  a
1   2  23.40  b
2   3  34.40  c
3   4  54.40  d
4   5  65.40  e
5   6  67.90  f
6   7  78.80  g
7   8  98.60  h
8   9  11.40  i
9  10  45.47  j

In [0]:
### selecting data from dataframe
###1.loc   2.iloc

In [48]:
dd["c2"]   ##column c2

0    12.10
1    23.40
2    34.40
3    54.40
4    65.40
5    67.90
6    78.80
7    98.60
8    11.40
9    45.47
Name: c2, dtype: float64

In [54]:
dd[["c2","c2"]]  # for multiple columns df_name[[]]

c2     c2
0  12.10  12.10
1  23.40  23.40
2  34.40  34.40
3  54.40  54.40
4  65.40  65.40
5  67.90  67.90
6  78.80  78.80
7  98.60  98.60
8  11.40  11.40
9  45.47  45.47

In [57]:
dd.loc[:,"c1"]  #using loc

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: c1, dtype: int64

In [56]:
dd.loc[:3,["c1","c2"]]  #location

c1    c2
0   1  12.1
1   2  23.4
2   3  34.4
3   4  54.4

In [58]:
dd.iloc[:,0]  #indexed location 

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: c1, dtype: int64

In [59]:
dd.iloc[:4,:1]

c1
0   1
1   2
2   3
3   4

In [60]:
### Retriving the information from dataframe
dd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   c1      10 non-null     int64  
 1   c2      10 non-null     float64
 2   c3      10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [61]:
dd.shape # (r,c)

(10, 3)

In [62]:
dd.columns

Index(['c1', 'c2', 'c3'], dtype='object')

In [63]:
dd.index

RangeIndex(start=0, stop=10, step=1)

In [0]:
### Viewing data from DF:
# 1.head()
# 2.tail()
# 3.sample()


In [65]:
dd.head()   # first 5 rows

c1    c2 c3
0   1  12.1  a
1   2  23.4  b
2   3  34.4  c
3   4  54.4  d
4   5  65.4  e

In [66]:
dd.head(3)  #by default it is 5

c1    c2 c3
0   1  12.1  a
1   2  23.4  b
2   3  34.4  c

In [67]:
dd.tail()   #last 5

c1     c2 c3
5   6  67.90  f
6   7  78.80  g
7   8  98.60  h
8   9  11.40  i
9  10  45.47  j

In [68]:
dd.tail(3)    #last 3

c1     c2 c3
7   8  98.60  h
8   9  11.40  i
9  10  45.47  j

In [69]:
dd.sample()    #any 1 row

c1    c2 c3
5   6  67.9  f

In [71]:
dd.sample(3)     # any 3 random rows

c1    c2 c3
2   3  34.4  c
0   1  12.1  a
8   9  11.4  i

In [72]:
dd.describe()     #count,mean,std,min....for only numeric data

c1         c2
count  10.00000  10.000000
mean    5.50000  49.187000
std     3.02765  29.172916
min     1.00000  11.400000
25%     3.25000  26.150000
50%     5.50000  49.935000
75%     7.75000  67.275000
max    10.00000  98.600000

In [75]:
dd.rename(columns={"c1":"f","c2":"s","c3":"t"},inplace="True")
# for rename column names use dictionary
dd

f      s  t
0   1  12.10  a
1   2  23.40  b
2   3  34.40  c
3   4  54.40  d
4   5  65.40  e
5   6  67.90  f
6   7  78.80  g
7   8  98.60  h
8   9  11.40  i
9  10  45.47  j